### ISSUE TITLE
	Error:com.ibm.watson.developer_cloud.service.exception.BadRequestException: not enough text provided for language detection

### ISSUE THREAD

**Issue by markstur** [ragudiko/wks-nlu-sms-analysis#27] opened 2018-02-28 22:12 UTC
When analyzing a text -- we'll get this error unless we specify a language.
Options are:
  - default to English (we're probably assuming that anyway)
  - make it a try/fallback
  - make it configurable
  - leave it as-is, but at least handle the error and report it back

**Comment by markstur** [comment] 2018-03-02 04:10
The error is at least shown in the UI now.

**Comment by ragudiko** [comment] 2018-03-02 11:15
This is a very good observation. We would like to fix it be defaulting to English now, as our wks model is trained on English text. We will display info on UI saying your sms input should be in English language. Also if possible we will try to report back if non-English text is placed in input field.

**Comment by stevemar** [comment] 2018-03-13 05:33
Did #47 close this issue? cc @rhagarty

**Comment by rameshpoomalai** [comment] 2018-03-13 05:47
Hi @stevemart, @markstur  , The PR is to handle any error from NLU and report in the UI. I have tried with different languages but i am getting a empty response. Can you share the text you have used to test this issue. So that i can confirm it.

**Comment by rameshpoomalai** [comment] 2018-03-13 06:21
Hi @stevemart @markstur ,
When i try to input very short text then i am getting bellow error message: Error:com.ibm.watson.developer_cloud.service.exception.ServiceResponseException: not enough text for language id 
But i am not able to reproduce the BadRequestException

**Comment by rhagarty** [comment] 2018-03-13 14:49
@stevemart - #47 did not specifically address this issue, but like @rameshpoomalai, I am unable to recreate the original error message. To me, this doesn't seem like a big deal as error is explicit enough for user to understand the issue. I propose we close this.

**Closed as completed** 2018-03-16 15:08 UTC
